version: '2'
services:
  flask_kafka:
    build: .
    image: adrianovieira/flask_kafka:debian8
    ports:
     - "80:80"
    volumes:
     - ./code:/var/www/html
    depends_on:
     - kafka
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOSTNAME}
      KAFKA_ADVERTISED_PORT: 9092
